import { StyleSheet } from 'react-native';
import { Color } from './Color';

export const GlobalStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Color.fondo,
        alignItems: 'center',
        justifyContent: 'flex-end',
        paddingBottom: 20,
    },
    fila: {
        flexDirection: 'row',
        justifyContent: "space-around",
        marginBottom: 16,
        paddingHorizontal: 10,
        width: '100%',
    },
    boton: {
        width: 80,
        textAlign: 'center',
        padding: 10,
        fontSize: 30,
        fontWeight: 400,
        backgroundColor: Color.blancoFondo,
        borderColor: Color.negro,
        color: Color.negro,
        borderWidth: 2,
        borderRadius: 40,
    },
    boton0: {
        width: 160,
        textAlign: 'center',
        padding: 10,
        fontSize: 30,
        fontWeight: 400,
        backgroundColor: Color.blancoFondo,
        borderColor: Color.negro,
        color: Color.negro,
        borderWidth: 2,
        borderRadius: 40,
    },
    botonOperador: {
        width: 80,
        textAlign: 'center',
        padding: 10,
        fontSize: 30,
        fontWeight: 400,
        backgroundColor: Color.rojoOperaciones,
        borderColor: Color.negro,
        borderWidth: 2,
        borderRadius: 40,
    },
    botonResto: {
        width: 80,
        textAlign: 'center',
        padding: 10,
        fontSize: 30,
        fontWeight: 400,
        backgroundColor: Color.grisResto,
        borderColor: Color.negro,
        borderWidth: 2,
        borderRadius: 40,
    },
    pantallaPrincipal: {
        fontSize: 70,
        textAlign: 'right',
        fontWeight: 500,
        width: '90%',
    },
    pantallaSecundaria: {
        fontSize: 40,
        textAlign: 'right',
        width: '90%',
    },

});